### ISSUE TITLE
Bower package

### ISSUE THREAD

**Issue by FluorescentHallucinogen** [GoogleChrome/imagecapture-polyfill#5]
Please publish this polyfill in Bower registry.

**Comment by dandv** [comment]
Given that bower [has](https://github.com/Polymer/polymer/issues/326#issuecomment-26827833) [been](https://www.quora.com/Why-use-Bower-when-there-is-npm) [going](https://medium.com/@nickheiner/why-my-team-uses-npm-instead-of-bower-eecfe1b9afcb) [away](https://gofore.com/stop-using-bower/), I'm reluctant to publish this package in the Bower registry.

**Comment by dandv** [comment]
Now that Bower has now been [officially deprecated](https://github.com/bower/bower/issues/2298#issuecomment-302792690), I will close this issue.
