### ISSUE TITLE
Minified version

### ISSUE THREAD

**Issue by FluorescentHallucinogen** [GoogleChrome/imagecapture-polyfill#6]
Please add minified version (`lib/imagecapture.min.js`) to the package.

**Comment by FluorescentHallucinogen** [comment]
@dandv PTAL.

**Comment by dandv** [comment]
Thanks for the ping. I've added a minified version and will publish a new package version to npm as soon as yarn releases the [fix for `yarn publish`](https://github.com/yarnpkg/yarn/issues/3831#issuecomment-313717492).

**Comment by imerkle** [comment]
you can also just do npm publish

**Comment by dandv** [comment]
@dsslimshaddy: I had actually [uninstalled npm](https://github.com/eslint/eslint/issues/8787#issuecomment-310720832), but I've [just published v0.3.4](https://www.npmjs.com/package/image-capture).
